spring:
  config: 
    activate:
      on-profile:
        dev
  data:
    mongodb:
      uri: mongodb://spring:password1234@mongodb-books:27017/booksonline
  
server:
  port: 8081
  servlet:
    context-path:
           
eureka:
  client:
    service-url:
      #defaultZone: http://eureka-server:8761/eureka/
      defaultZone: ${EUREKASERVER_URI}
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5      
