spring:
  application:
    name: frontend-service
  config:
    activate:
      on-profile:
      - dev
    import:
      "optional:configserver:http://config-server:8888/"          
 
server:
  port: 8080
  servlet:
    context-path: /gutenberg
    
---

spring:
  application:
    name: frontend-service
  config:
    activate:
      on-profile:
      - default
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


# base server URLs 
#baseBooksUrl: http://gateway-service:5555/books
gutenberg:
  baseBooksUrl: http://localhost:5555/books
  baseReviewsUrl: http://localhost:5555/reviews
  baseOrdersUrl: http://localhost:5555/orders
  baseUsersUrl: http://localhost:5555/users       
      