#!/bin/bash

for server in 'book-server' 'order-server' 'review-server' 'user-server'; 
do 
  echo ${server}
    pwd
    cd booksonline
    pwd
    echo "./booksRestore"
    ./booksRestore
    cd ../../$server
    pwd
    echo "./build"
    ./build
    cd ../dockerbuild
   
    echo $?
    if [ "$?" -ne 0 ]
    then 
      echo "Build failed for $server"
      exit "$?"
    fi  

done;
echo "Now building cloud and frontend "
for server in 'eureka-server' 'gateway-server' 'config-server' 'frontend-server';
do 
  echo ${server}
    cd ../$server  
    pwd
    echo "./build"
    ./build
    
    echo $?
    if [ "$?" -ne 0 ]
    then 
      echo "Build failed for $server"
      exit "$?"
    fi  

done;


